### ISSUE TITLE
Cannot launch mmSolver import marker action v0.3.13

### ISSUE THREAD

**Issue by tlhommeperso** [david-cattermole/mayaMatchMoveSolver#215] opened 2021-03-29 16:22 UTC
### Problem / Feature
When clicking the load marker action, an error occurs and the window to import markers fails to open, hence i am currently unable to use mmSolver 
`# Error: AttributeError: file C:\Users\thoma\Documents\maya\2020\modules\mayaMatchMoveSolver-0.3.13-maya2020-win64\python\mmSolver\tools\loadmarker\ui\loadmarker_layout.py line 83: 'module' object has no attribute 'QStringListModel' # 
`
**Expected behavior:**
The window to import 2d markers should open on clikc allowing us to either import from file or clipboard

**Actual behavior:**
Nothing heppends and an error message get's printed out in the script editor

### Steps to Reproduce

1. open maya
2. go on mmSolver menu and click "load markers"

### Software Versions
- mmSolver version:
v0.3.13
- Maya version:
Maya 2020.4

Cut ID: 202011110415-b1e20b88e2
Maya Version: Autodesk Maya 2020.4
Maya API: 20200400
Qt Version: 5.12.5
Compositing Manager: True
Window Manager: Windows Aero
GPU:   Version : 2016.11.53.12. Feature Level 5.
  Adapter : GeForce RTX 2060 SUPER/PCIe/SSE2
  Vendor ID: 4318. Device ID : 7942
  Driver : .
  API : OpenGL V.4.6.
  Max texture size : 16384 * 16384.
  Max tex coords : 32
  Shader versions supported (Vertex: 5, Geometry: 5, Pixel 5).
  Shader compiler profile : (Best card profile)
  Active stereo support available : 0
  GPU Memory Limit : 8192 MB.
  CPU Memory Limit: 31047.5 MB.

- Operating System (OS):
Operating System: Microsoft Windows 10 Technical Preview  (Build 19042)

**Comment by david-cattermole** [comment] 2021-03-29 18:55
Thank you for the fast testing and report. I'm sorry I didn't catch this :/

I will have a closer look at this hopefully in a few hours and will try to re-upload as soon as possible.

David

**Comment by david-cattermole** [comment] 2021-03-29 20:48
@tlhommeperso, I have found the problem and patched the issue for Windows only, and re-uploaded.

You can download the updated .zip file here:
https://github.com/david-cattermole/mayaMatchMoveSolver/releases/download/v0.3.13/mayaMatchMoveSolver-0.3.13-maya2020-win64.zip

Or from the release page:
https://github.com/david-cattermole/mayaMatchMoveSolver/releases/tag/v0.3.13

I will patch the Linux version tomorrow, and update the documentation. Once all the versions are updated and the code is properly fixed I will close this ticket, but this patch should get you going on Windows at least.

Thanks for reporting!

David

---------------- 

P.S. For other people finding this same problem....

This problem is caused by the move from Qt 5.6.x to Qt 5.12.x, in Maya 2020.
`Qt 5.12.x` fixed a bug by moving `PySide.QtGui.QStringList` to `PySide.QtGui.QStringList`, but `Qt.py 1.1.0` already had a fix for this and does not expect the bug fix to be applied. 
The fix for this issue is to update to `Qt.py 1.2.0` which supports both `Qt 5.12.x`, and older versions as well.

The issue reported here was of great help (thanks!):
https://github.com/mottosso/Qt.py/issues/298

**Comment by david-cattermole** [comment] 2021-03-30 23:07
I have now updated the Linux .tar.gz archive for Maya 2020, so now both the Windows and Linux downloads are patched.

@tlhommeperso Can you confirm this works for you? It works for me on my end on both Windows 10 and Linux (CentOS 7.x).

**Comment by david-cattermole** [comment] 2021-06-26 21:51
@tlhommeperso I'm going to assume this is now fixed for you, as I have tested it and it's working for me.

Closing, please re-open if it's not working.

**Closed by david-cattermole** 2021-06-26 21:51 UTC
Labels: bug
