### ISSUE TITLE
Solver UI - Incorrect object gets added to solver in v0.3.8

### ISSUE THREAD

**Issue by RodeoPerchaude** [david-cattermole/mayaMatchMoveSolver#165] opened 2020-10-22 19:48 UTC
Hello all, following a conversation with Patcha, I am creating a"ticket" on the board.
Let me know if I am doing it wrong, and thanks for looking into it eventually.
Aside from this issue, 0.38 has been really stable for me so far. 
14-20 hours without issues.

### Problem / Feature
When selecting an object and adding it to the solver output attributes, another unrelated object gets added in it's place.

Exemple: 
selecting: characterBucky_001:R_arm_1_FK_CON
added to the solver: characterBucky_001:R_foot_IK_CON

### Steps to Reproduce
![31313123](https://user-images.githubusercontent.com/73302174/96921999-47066100-147d-11eb-9e47-84a0fdd66b10.gif)

### Software Versions
Maya 2018.6

- mmSolver version:
0.38

- Maya version:
Maya 2018.6

- Operating System (OS): Rodeo's centOs

**Comment by david-cattermole** [comment] 2020-10-22 23:55
Hello Etienne,

This is obviously a bug, and was meant to be fixed by #153.
I'm not sure what's causing it (yet), but I will investigate and I will release a v0.3.9 as soon as I can.

Is it possible to send me a scene file that reproduces the problem?
I don't need models at all, just the outer rig controls - only enough to reproduce the problem.

If I don't have any scene file, I can still attempt to fix the problem blindly but I have not way of testing myself.
I could produce a new pre-release of v0.3.9 with my changes for Maya 2018 on (CentOS) Linux, then you can test and let me know?

David

**Comment by RodeoPerchaude** [comment] 2020-10-23 12:30
Hello David, I considered including the scene files, but the rig is running
on prioritary plugins only compiled for our os at rodeo.

I'll try and reproduce the hell issue without any fancy rigs loaded in!

**Comment by david-cattermole** [comment] 2020-11-02 05:04
@RodeoPerchaude 

I have a possible solution to this problem, and it will be released in v0.3.9 (soon).

Once it's released, please let me know if the problem is fixed or not.

David

**Comment by RodeoPerchaude** [comment] 2020-11-02 13:45
My pleasure David, We will install 0.3.9 as soon as possible and see if the issue is resolved.
Merci!

**Comment by david-cattermole** [comment] 2020-11-24 19:28
@RodeoPerchaude can you confirm if this is working for you? Or maybe try v0.3.10?

**Comment by david-cattermole** [comment] 2020-12-07 21:04
I know a lot more information about this bug now! It seems the problem is caused by duplicate UUIDs on the nodes.

By default each node in Maya will have different UUID values. However, if you create a scene file with a UUID, `A`, then reference that scene file into another scene file the same node will have the same UUID because a referenced file is never changed - that is usually fine... However, when you reference in the same scene file you will have two referenced files, with two differently named nodes, with the same UUID.

A lot of mmSolver assumes that two nodes can always be fetched with the UUID, and there is only one node with the same UUID.
Now I realise this is not true. I will need to do some research to fix this issue... but at least I know what the problem is.

David

**Comment by RodeoPerchaude** [comment] 2020-12-07 21:24
Thanks a lot for the detective work David and Patcha.
I will make sure we have proper and unique UUID on our rigs and we would be good to go!

**Comment by david-cattermole** [comment] 2020-12-11 00:02
Hello @RodeoPerchaude,

I have researched this bug and I've implemented a fix which will be ready in v0.3.11 (hopefully out this weekend).

Just to be clear, forcing the rig to have unique UUIDs will not stop this problem happening 100%.

If you load the rig file `Character.mb` into your Maya scene twice, the
same controls in each respective reference will have the same UUID
and the bug will happen.

My fix will stop the duplicate UUIDs for Attributes in the Solver from causing weirdness.
Technically, although extremely impractical, this fix will not stop the same problem happening with Markers, Bundles, Cameras and Collections. It is assumed that users do not use Markers (etc) inside referenced scene files.

David

**Closed by david-cattermole** 2020-12-11 00:02 UTC
Labels: bug, maya tool
