### ISSUE TITLE
Basic Solver not Working, Maya 2023.3 

### ISSUE THREAD

**Issue by ubern093** [david-cattermole/mayaMatchMoveSolver#248] opened 2023-07-24 21:36 UTC
### Problem or Feature
Hello, i'm trying to learn the tool usage, in order to do so i downloaded the material for the RobotArm available on the channel, 
since i'm using maya 2023.3 and MMSolver 0.4.5 i've tracked the scene from scratch in 3DE and made my own set of markers,
Unfortunately following the workflow of the video i am unable to get the Basic Solve to work for me.

**Expected behavior:**
as i am trying to solve the first arm animation on the Rot Y of the control i expect the solve to give me an aproximate result based on my rough animation and the markers. 

**Actual behavior:**

// Warning: mmSolver._api._execute.main : Invalid parameters and errors (param=0 errors=4 frames=387), skipping solve (for all the frames) 
// mmSolver.tools.solver.lib.collection : Total Time: 0:0.86s  (0.00 fps)
// mmSolver.tools.solver.lib.collection : Max Frame Deviation: -0.00 pixels at frame None
// mmSolver.tools.solver.lib.collection : Average Deviation: 0.00 pixels
// Warning: mmSolver.tools.solver.lib.collection : 2023-07-24 17:22:55 | Solved 0 frames | Average Deviation 0.00px | Max Deviation -0.00px at fNone | Time 0:0.86s (0.00 fps)

### Steps to Reproduce

1. I've created the scene from scratch imported my .mel script with the Camera from 3DE, followed the video to roughly place and animate the robotic arm. 
2. Always following the video i've parented the Bundles under the Control i wish to solve, placed the Bundles where they should be on the 3D model, and followed every step showed in the video. 
3. When i get to run the first Basic Solve on the First_CTRL i get the error i've pasted above. 

### Software Versions

- mmSolver version: 0.4.5

- Maya version:
2023.3

- Operating System (OS): Windows 11

<img width="897" alt="image" src="https://github.com/david-cattermole/mayaMatchMoveSolver/assets/48280979/fb5d3b3f-f0b6-4343-b047-f1f4baa7e493">

**Comment by ubern093** [comment] 2023-07-25 20:13
Hi Again @david-cattermole 

I can confirm that both the workaround you suggested works, the standard solver gives more unexpected/glitchy results than the basic solve + evaluate mesh rivets checked.

Thanks for your prompt reply, and help! 

I will be waiting for the solution and will be available to try it again on my end!

**Comment by david-cattermole** [comment] 2023-09-03 13:12
Hello @ubern093,

I have found the underlying issue that was causing your problem and I've added a fix that will be included in v0.4.6.
A test has been added as well that should catch this issue from coming up again.

The bug came from the fact that a single attribute parameter was being solved per-frame. If possible, adding a second attribute might have fixed the issue. The bug was caused by incorrectly counting the number of parameters that was available to the solver.

Thanks again for reporting this @ubern093!

**Closed by david-cattermole** 2023-09-03 13:12 UTC
Labels: bug, question, core solver

**Comment by david-cattermole** [comment] 2023-10-10 13:25
@ubern093 v0.4.6 is now released and contains the bug fix for this issue;
https://github.com/david-cattermole/mayaMatchMoveSolver/releases/tag/v0.4.6

**Comment by ubern093** [comment] 2023-10-10 20:10
Thanks for the Update I will be Testing on my side with the new version in
the next days,
It was a pleasure to help the development and thanks for the very prompt
implementation
as well for the temporary solution!

Ruben



Il giorno mar 10 ott 2023 alle ore 09:25 David Cattermole <
***@***.***> ha scritto:
